services:
  database:
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    depends_on:
      database:
        condition: service_healthy
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_DB: "database"
      POSTGRES_HOST: "database"
    ports:
      - 8080:8080
