"""empty message

Revision ID: d1fbdd091d1a
Revises:
Create Date: 2023-03-30 14:46:01.596175

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1fbdd091d1a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.create_table(
        "participant",
        sa.Column("participant_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("wish", sa.String(), nullable=True),
        sa.Column("recipient_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["participant.participant_id"],
        ),
        sa.PrimaryKeyConstraint("participant_id"),
    )
    op.create_index(op.f("ix_participant_participant_id"), "participant", ["participant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_participant_participant_id"), table_name="participant")
    op.drop_table("participant")
    op.drop_index(op.f("ix_group_id"), table_name="group")
    op.drop_table("group")
    # ### end Alembic commands ###
